version: '3'

services:
  php:
    container_name: php
    build: ./php
    image: dat_php
    depends_on:
      - db
    restart: always
    volumes:
    - ../laravel:/var/www/html

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
    - ${HTTP_PORT}:80
    volumes:
    - ../laravel:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
    restart: always
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    - ./db/logs:/var/log/mysql

  redis:
    image: redis:5-alpine
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
